# Generated by Django 3.1.5 on 2021-02-15 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20210215_1547'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='max_bid',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='starting_bid',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='winner',
        ),
    ]
